# Navigation Links

main:
  - name: Sobre
    url: '#about'
    weight: 10
  - name: Blog
    url: '#posts'
    weight: 20
  - name: Projetos
    url: '#projects'
    weight: 30
  - name: Contato
    url: '#contact'
    weight: 40
