# Navigation Links

main:
  - name: Sobre
    url: '#sobre'
    weight: 10
  - name: Blog
    url: '#blog'
    weight: 20
  - name: Projetos
    url: '#projetos'
    weight: 30
  - name: Contato
    url: '#contato'
    weight: 40
