# Site Setup

# Appearance

theme: minimal
day_night: true
font: ''
font_size: L

# SEO

site_type: Person
description: 'Site pessoal de Marcos Vinicius de Paula Alves'


# Contact (edit or remove options as required)

email: macvinny@protonmail.com
address:
  city: Goiânia
  region: Goiás
  country: Brasil
  country_code: BR

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: '02/01/2006'
time_format: '15:04'
address_format: pt-br

# Site features

highlight: true
highlight_languages:
  - c
  - java
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/macvinny/site/'
  content_dir: ''
  repo_branch: main
  editable:
    page: true
    post: true
    book: true
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: square
publications:
  date_format: 01/2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
search:
  provider: wowchemy
icon:
  pack:
    ai: true
