# Site Setup

# Appearance

appearance:
theme_day: minimal
theme_night: minimal
font: minimal
font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''Site pessoal de Marcos Vinicius de Paula Alves''
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Contact (edit or remove options as required)

email: macvinny@protonmail.com
address:
  city: Goiânia
  region: Goiás
  country: Brasil
  country_code: BR

# Site header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
      

# Localization
locale:
  date_format: '02/01/2006'
  time_format: '15:04'
  address_format: pt-br
  
# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - c
      - java
  math:
    enable: true
  diagram:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/macvinny/site/'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: square
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
